geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductReadView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name = 'login'),
    path('logout/', authapp.logout, name = 'logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('contacts/', include('contactsapp.urls', namespace='contacts')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/geekshop/views.py
from django.shortcuts import render
from basketapp.models import Basket
from mainapp.models import Product
from contactsapp.models import Contact

def main(request):
    title = 'Магазин'
    basket = []
    products = Product.objects.all()
    contacts = Contact.objects.all()

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    context = {
        'title': title,
        'products': products,
        'contacts': contacts,
        'basket': basket,
    }
    return render(request, 'geekshop/index.html', context)

geekshop/geekshop/templates/geekshop/includes/menu.html
{% load static %}
<div class="hero-white">
    <div class="header clearfix">
        <a href="{% url 'main' %}" class="logo"></a>
        <ul class="menu">
            <li><a href="{% url 'main' %}" class="
                    {% if request.resolver_match.view_name == 'main' %}
                        active
                    {% endif %}">домой</a>
            </li>
            <li><a href="{% url 'products:main' %}" class="
                    {% if request.resolver_match.view_name == 'products:main' %}
                        active
                    {% endif %}">продукты</a></li>
            <li><a href="{% url 'contacts:main' %}" class="
                    {% if request.resolver_match.view_name == 'contacts:main' %}
                        active
                    {% endif %}">контакты</a>
            </li>
            {% if user.is_authenticated %}
                <li class="dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                     <a>{{ user.first_name|default:'Пользователь' }}</a>
                </li>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="{% url 'auth:edit' %}">Профиль</a></li>
                    {% if user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'admin_staff:users' %}">Админка</a></li>
                    {% endif %}
                    {% if basket %}
                        <li><a class="dropdown-item" href="{% url 'basket:view' %}">Корзина</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Выйти</a></li>
                    {% endif %}
                </ul>
                {% if basket %}
                    <li>
                        <span>

                        {{ basket.0.total_cost|floatformat:0 }} руб.
                        ({{ basket.0.total_quantity  }} шт.)
                    </span>
                    </li>

                {% endif %}
            {% endif %}
            {% if not user.is_authenticated %}
                <li>
                    <a href="{% url 'auth:login' %}">Войти</a>
                </li>
            {% endif %}
        </ul>
        <a href="#" class="search"></a>
    </div>
</div>

geekshop/geekshop/templates/geekshop/includes/slider.html
{% load static %}
<div class="slider">

    <div class="text-slider">
        <h3 class="green">тенденции {% now "Y" %}</h3>
        <h3 class="big">удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">заказать <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a>
        <a href="#"></a>
        <a href="#"></a>
    </div>
</div>