geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductReadView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name = 'login'),
    path('logout/', authapp.logout, name = 'logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('contacts/', include('contactsapp.urls', namespace='contacts')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from django.forms import ModelForm

from mainapp.models import Product, ProductsCategory


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductEditForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class CategoryCreationForm(ModelForm):
    class Meta:
        model = ProductsCategory
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super(CategoryCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class CategoryEditForm(ModelForm):
    class Meta:
        model = ProductsCategory
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super(CategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from adminapp.forms import ShopUserAdminEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from django.shortcuts import get_object_or_404, render, reverse
from adminapp.forms import CategoryCreationForm, CategoryEditForm
from mainapp.models import Product, ProductsCategory
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

class UsersListView(LoginRequiredMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'
    login_url = '/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UsersListView, self).get_context_data()
        context['title'] = 'админка/пользователи'
        return context

    # @method_decorator(user_passes_test(lambda u: u.is_superuser))
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     context = {
#         'title': title,
#         'objects': users_list
#     }
#
#     return render(request, 'adminapp/users.html', context)

class UserCreateView(LoginRequiredMixin, CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

# def user_create(request):
#     title = 'пользователи/создание'
#
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES )
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#
#     context = {
#         'title': title,
#         'user_form': user_form
#     }
#
#     return render(request, 'adminapp/user_update.html', context)

class UserUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserAdminEditForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

# def user_update(request, pk):
#     title = 'пользователи/редактирование'
#
#     edit_user = get_object_or_404(ShopUser, pk=pk )
#
#     if request.method == 'POST':
#         edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
#
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:user_update', args=[edit_user.pk]))
#     else:
#         edit_form = ShopUserAdminEditForm(instance=edit_user)
#
#     context = {
#         'title': title,
#         'edit_form': edit_form
#     }
#
#     return render(request, 'adminapp/user_update.html', context)

class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

# def user_delete(request, pk):
#     title = 'пользователи/удаление'
#
#     user = get_object_or_404(ShopUser, pk=pk)
#
#     if request.method == 'POST':
#         user.is_active = False
#         user.save()
#
#     context = {
#         'title': title,
#         'user_to_delete': user
#     }
#
#     return render(request, 'adminapp/user_delete.html', context)

class CategoryListView(LoginRequiredMixin, ListView):
    model = ProductsCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'
    login_url = '/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data()
        context['title'] = 'админка/категории'
        return context

# def categories(request):
#     title = 'админка/категории'
#
#     categories_list = ProductsCategory.objects.all()
#
#     context = {
#         'title': title,
#         'objects': categories_list
#     }
#
#     return render(request, 'adminapp/categories.html', context)

class CategoryCreateView(CreateView):
    model = ProductsCategory
    form_class = CategoryEditForm
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryCreateView, self).get_context_data()
        context['title'] = 'категория/создание'
        return context

# def category_create(request):
#     title = 'категория/создание'
#
#     if request.method == 'POST':
#         category_form = CategoryCreationForm(request.POST, request.FILES)
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#     else:
#         category_form = CategoryCreationForm()
#
#     context = {
#         'title': title,
#         'category_form': category_form
#     }
#
#     return render(request, 'adminapp/category_create.html', context)

class CategoryUpdateView(UpdateView):
    model = ProductsCategory
    form_class = CategoryEditForm
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data()
        context['title'] = 'категория/редактирование'
        return context

# def category_update(request, pk):
#     title = 'категория/редактирование'
#     edit_category = get_object_or_404(ProductsCategory, pk=pk)
#
#     if request.method == 'POST':
#         edit_form = CategoryEditForm(request.POST, request.FILES, instance=edit_category)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:category_update', args=[edit_category.pk]))
#     else:
#         edit_form = CategoryEditForm(instance=edit_category)
#
#     context = {
#         'title': title,
#         'category_form': edit_form,
#     }
#
#     return render(request, 'adminapp/category_update.html', context)


class CategoryDeleteView(DeleteView):
    model = ProductsCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryDeleteView, self).get_context_data()
        context['title'] = 'категория/удаление'
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


# def category_delete(request, pk):
#     title = 'категория/удаление'
#
#     category = get_object_or_404(ProductsCategory, pk=pk)
#
#     if request.method == 'POST':
#         category.is_active = False
#         category.save()
#
#     context = {
#         'title': title,
#         'category_to_delete': category
#     }
#
#     return render(request, 'adminapp/category_delete.html', context)

class ProductsListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'adminapp/products.html'
    context_object_name = 'objects'
    login_url = '/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['title'] = 'админка/продукты'
        context['category'] = get_object_or_404(ProductsCategory, pk=self.kwargs['pk'])
        context['products_list'] = self.object_list.filter(category__pk=self.kwargs['pk']).order_by('name')
        return context

# def products(request, pk):
#     title = 'админка/продукт'
#     category = get_object_or_404(ProductsCategory, pk=pk)
#     products_list = Product.objects.filter(category__pk=pk).order_by('name')
#
#     context = {
#         'title': title,
#         'category': category,
#         'objects': products_list,
#     }
#
#     return render(request, 'adminapp/products.html', context)

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/product_update.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCreateView, self).get_context_data()
        context['title'] = 'продукт/создание'
        context['category'] = get_object_or_404(ProductsCategory, pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', args=[self.object.category_id])



# def product_create(request, pk):
#     title = 'продукт/создание'
#     category = get_object_or_404(ProductsCategory, pk=pk)
#
#     if request.method == 'POST':
#         product_form = ProductEditForm(request.POST, request.FILES)
#         if product_form.is_valid():
#             product_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:products', args=[pk]))
#     else:
#         product_form = ProductEditForm(initial={'category': category})
#
#     context = {
#         'title': title,
#         'product_form': product_form,
#         'category':category,
#     }
#
#     return render(request, 'adminapp/product_update.html', context)

class ProductReadView(ListView):
    model = Product
    template_name = 'adminapp/product_read.html'

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<!--{#        <link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">#}-->
        <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">
        <link rel="stylesheet" type="text/css"href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">

    {% block css %}
    {% endblock %}

    <script src='{% static "adminapp/js/script.js" %}'></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'main' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'adminapp/includes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Продукты</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Название категории</th>
                                <th>Описание</th>
                                <th>Редактировать</th>
                                <th>Активный</th>
                                <th>Удалить</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Название категории</th>
                                <th>Описание</th>
                                <th>Редактировать</th>
                                <th>Активный</th>
                                <th>Удалить</th>
                            </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                            <tr {% if not category.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:products' category.pk %}" style="color: dodgerblue">{{ category.name }}</a></td>
                                <td>{{ category.description }}</td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:category_update' category.id %}" style="color: dodgerblue"><i class="fa fa-ellipsis"></i></a>

                                </td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    <a {% if not category.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:category_delete' pk=category.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post", enctype="multipart/form-data">
        {% csrf_token %}
        {{ category_form }}
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="category_delete">
    Уверены, что хотите удалить {{ object.name }} ?
    <form action="{% url 'admin_staff:category_delete' object.pk %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_delete">
    Уверены, что хотите удалить {{ product_to_delete.name }} ?
    <form action="{% url 'admin_staff:product_delete' product_to_delete.pk %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:products' product_to_delete.category.pk %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="card product-read">
  <img src="{{ object.image|media_folder_products }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ object.name }}</h5>
    <p class="card-text">{{ object.description }}</p>
    <p class="card-text">Цена {{ object.price }} руб.</p>
    <p class="card-text">На складе {{ object.quantity }} шт.</p>

  </div>

</div>
<a href="{% url 'admin_staff:product_update' object.pk %}" class="btn btn-primary">Редактировать</a>
<a href="{% url 'admin_staff:products' category.pk %}" class="btn btn-primary">Назад</a>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Продукты</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Продукты категории {{ category.name }}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Наименвание</th>
                                <th>Детали</th>
                                <th>Количество</th>
                                <th>Стоимость</th>
<!--                                <th>Редактировать</th>-->
                                <th>Активный</th>
                                <th>Удалить</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Наименвание</th>
                                <th>Детали</th>
                                <th>Количество</th>
                                <th>Стоимость</th>
<!--                                <th>Редактировать</th>-->
                                <th>Активный</th>
                                <th>Удалить</th>
                            </tr>
                        </tfoot>
                        <tbody>
                        {% for product in products_list %}
                            <tr {% if not product.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td>{{ product.name }}</td>
                                <td><a href="{% url 'admin_staff:product_read' product.pk %}">Подробнее</a></td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.price }}</td>
<!--                                <td class="text-center">-->
<!--                                    <a href="{% url 'admin_staff:product_update' product.pk %}" style="color: dodgerblue"><i class="fa fa-ellipsis"></i></a>-->

<!--                                </td>-->
                                <td class="text-center">
                                    {% if product.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    <a {% if not product.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:product_delete' pk=product.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:product_create' category.pk %}">
                    <button class="btn btn-success">Создать продукт</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ object.username }}
    {% if object.first_name %}
      ({{ object.first_name|title }}</b>
      {% if object.last_name %}
        {{ object.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin_staff:user_delete' object.pk %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in objects %}
                            <tr {% if not user.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td>
                                    <a {% if not user.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}