geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name = 'login'),
    path('logout/', authapp.logout, name = 'logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('contacts/', include('contactsapp.urls', namespace='contacts')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name = 'main'),
    path('category/<int:pk>', products, name = 'category'),
    path('product /<int:pk>', product, name = 'detail'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class ProductsCategory(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name='имя',
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(
        max_length=128,
        verbose_name='имя продукта',
    )

    image = models.ImageField(
        upload_to='products_images',
        blank=True,
    )

    category = models.ForeignKey(
        ProductsCategory,
        on_delete=models.CASCADE,
    )

    short_desc = models.CharField(
        max_length=60,
        verbose_name='краткое описание',
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
    )

    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='цена',
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/forms.py
from django.forms import ModelForm
from mainapp.models import Product, ProductsCategory

geekshop/mainapp/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductsCategory, Product
from basketapp.models import Basket
import random


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []

def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]

def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None, page=1):
    title = 'Каталог'
    links_menu = ProductsCategory.objects.all()
    basket = get_basket(request.user)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')

    if pk is not None:
        if pk == 0:
            category = {'pk': 0, 'name': 'все'}
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductsCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

        paginator = Paginator(products, 1)

        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'basket': basket,
        }
        return render(request, 'mainapp/products.html', context )

    context = {
        'title': title,
        'links_menu': links_menu,
        'products': products,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }
    return render(request, 'mainapp/products.html', context)

def product(request, pk):
    title = 'Описание товара'
    links_menu = ProductsCategory.objects.all()
    product = get_object_or_404(Product, pk=pk)
    same_products =  get_same_products(product)
    basket = get_basket(request.user)

    context = {
        'title': title,
        'links_menu': links_menu,
        'product': product,
        'same_products': same_products,
        'basket': basket,
    }
    return render(request, 'mainapp/product.html', context)

geekshop/mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href= "{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
	{% include 'geekshop/includes/menu.html' %}
	<div class="details">
		<div class="links clearfix">
			<ul class="links-menu">
				<li><a href="{% url 'products:category' 0 %}" class="
						{% if request.resolver_match.kwargs.pk == 0 %}
							active
						{% endif %}">Все</a>
				</li>
				{% for link in links_menu %}
					<li><a href="{% url 'products:category' link.pk %}" class="
						{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
							active
						{% endif %}">{{ link.name }}</a>
					</li>
				{% endfor %}
			</ul>
		</div>
		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="/media/{{ product.image }}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll1.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll2.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>
			<div class="description">
				<h3 class="big-bold">{{ product.name }}</h3>
				<p class="price"> {{ product.price }} <span>руб</span></p>
				<a href="{% url 'basket:add' product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>{{ product.description }}</p>
				</div>
			</div>
		</div>
		{% if same_products %}
			<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все<img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				{% for same_product in same_products %}
					<div class="block">
						<a href="#"><img src="/media/{{ same_product.image }}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ same_product.name }}</h4>
								<p>{{ same_product.description }}</p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>
		{% endif %}
	</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href= "{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
	{% include 'geekshop/includes/menu.html' %}
	<div class="details">
		<div class="links clearfix">
			<ul class="links-menu">
				<li><a href="{% url 'products:category' 0 %}" class="
						{% if request.resolver_match.kwargs.pk == 0 %}
							active
						{% endif %}">Все</a>
				</li>
				{% for link in links_menu %}
					<li><a href="{% url 'products:category' link.pk %}" class="
						{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
							active
						{% endif %}">{{ link.name }}</a>
					</li>
				{% endfor %}
			</ul>
		</div>
		{% if hot_product %}
			<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="/media/{{ hot_product.image }}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll1.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll2.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>
			<div class="description">
				<h3 class="big-bold">{{ hot_product.name }}</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> {{ hot_product.price }} <span>руб</span></p>
				<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>{{ hot_product.description }}</p>
				</div>
			</div>
		</div>
		{% endif %}
		<div class="products-list tab-content">
		  <div class="title clearfix">
			  {% if category  %}
				<h2>Категория: "{{ category.name|title }}"</h2>
			  {% endif %}
		  </div>
		  <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                        <
                    </a>
                {% endif %}
                <span class="current">
                                страница {{ products.number }} из
                                {{ products.paginator.num_pages }}
                              </span>
                {% if products.has_next %}
                    <a href="{% url 'products:page' category.pk products.next_page_number %}">
                        >
                    </a>
                {% endif %}
            </div>

		  <div class="category-products clearfix">

			{% for product in products %}
			  <div class="block">
				<a href="{% url 'products:detail' product.pk %}">
				  <img class="img-product" src="/media/{{ product.image }}" alt="product">
				  <div class="text">
					<img class="img-hover" src="{% static 'geekshop/img/icon-hover.png' %}" alt="hover">
					  <h4>{{ product.name }}</h4>
					  <p>{{ product.description }}</p>
				  </div>
				</a>
			  </div>
			{% endfor %}

		  </div>
		</div>
		{% if same_products %}
			<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все<img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				{% for same_product in same_products %}
					<div class="block">
						<a href="{% url 'products:detail' same_product.pk %}"><img src="/media/{{ same_product.image }}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ same_product.name }}</h4>
								<p>{{ same_product.description }}</p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>
		{% endif %}
	</div>
{% endblock %}